let Colours = [
    {legoColourId:1,     name:'White',                   hex: '#F4F4F4', BrickLinkId: 1, BrickLinkName: 'White'},
    {legoColourId:5,     name:'Brick Yellow',            hex: '#B0A06F', BrickLinkId: 2, BrickLinkName: 'Tan'},
    {legoColourId:18,    name:'Nougat',                  hex: '#BB805A', BrickLinkId: 28, BrickLinkName: 'Nougat'},
    {legoColourId:21,    name:'Bright Red',              hex: '#B40000', BrickLinkId: 5, BrickLinkName: 'Red'},
    {legoColourId:23,    name:'Bright Blue',             hex: '#1E5AA8', BrickLinkId: 7, BrickLinkName: 'Blue'},
    {legoColourId:24,    name:'Bright Yellow',           hex: '#FAC80A', BrickLinkId: 3, BrickLinkName: 'Yellow'},
    {legoColourId:26,    name:'Black',                   hex: '#1B2A34', BrickLinkId: 11, BrickLinkName: 'Black'},
    {legoColourId:28,    name:'Dark Green',              hex: '#00852B', BrickLinkId: 6, BrickLinkName: 'Green'},
    {legoColourId:37,    name:'Bright Green',            hex: '#58AB41', BrickLinkId: 36, BrickLinkName: 'Bright Green'},
    {legoColourId:38,    name:'Dark Orange',             hex: '#91501C', BrickLinkId: 68, BrickLinkName: 'Dark Orange'},
    {legoColourId:102,   name:'Medium Blue',             hex: '#7396C8', BrickLinkId: 42, BrickLinkName: 'Medium Blue'},
    {legoColourId:106,   name:'Bright Orange',           hex: '#D67923', BrickLinkId: 4, BrickLinkName: 'Orange'},
    {legoColourId:119,   name:'Bright Yellowish Green',  hex: '#A5CA18', BrickLinkId: 34, BrickLinkName: 'Lime'},
    {legoColourId:124,   name:'Bright Reddish Violet',   hex: '#901F76', BrickLinkId: 71, BrickLinkName: 'Magenta'},
    {legoColourId:135,   name:'Sand Blue',               hex: '#70819A', BrickLinkId: 55, BrickLinkName: 'Sand Blue'},
    {legoColourId:138,   name:'Sand Yellow',             hex: '#897D62', BrickLinkId: 69, BrickLinkName: 'Dark Tan'},
    {legoColourId:140,   name:'Earth Blue',              hex: '#19325A', BrickLinkId: 63, BrickLinkName: 'Dark Blue'},
    {legoColourId:141,   name:'Earth Green',             hex: '#00451A', BrickLinkId: 80, BrickLinkName: 'Dark Green'},
    {legoColourId:151,   name:'Sand Green',              hex: '#708E7C', BrickLinkId: 48, BrickLinkName: 'Sand Green'},
    {legoColourId:154,   name:'New Dark Red',            hex: '#720012', BrickLinkId: 59, BrickLinkName: 'Dark Red'},
    {legoColourId:191,   name:'Flame Yellowish Orange',  hex: '#FCAC00', BrickLinkId: 110, BrickLinkName: 'Bright Light Orange'},
    {legoColourId:192,   name:'Reddish Brown',           hex: '#5F3109', BrickLinkId: 88, BrickLinkName: 'Reddish Brown'},
    {legoColourId:194,   name:'Medium Stone Grey',       hex: '#969696', BrickLinkId: 86, BrickLinkName: 'Light Bluish Gray'},
    {legoColourId:199,   name:'Dark Stone Grey',         hex: '#646464', BrickLinkId: 85, BrickLinkName: 'Dark Bluish Gray'},
    {legoColourId:212,   name:'Light Royal Blue',        hex: '#9DC3F7', BrickLinkId: 105, BrickLinkName: 'Bright Light Blue'},
    {legoColourId:221,   name:'Bright Purple',           hex: '#D3359D', BrickLinkId: 47, BrickLinkName: 'Dark Pink'},
    {legoColourId:222,   name:'Light Purple',            hex: '#FF9ECD', BrickLinkId: 104, BrickLinkName: 'Bright Pink'},
    {legoColourId:226,   name:'Cool Yellow',             hex: '#FFEC6C', BrickLinkId: 103, BrickLinkName: 'Bright Light Yellow'},
    {legoColourId:268,   name:'Medium Lilac',            hex: '#441A91', BrickLinkId: 268, BrickLinkName: 'Dark Purple'},
    {legoColourId:283,   name:'Light Nougat',            hex: '#FFC995', BrickLinkId: 90, BrickLinkName: 'Light Nougat'},
    {legoColourId:297,   name:'Warm Gold',               hex: '#AA7F2E', BrickLinkId: 115, BrickLinkName: 'Pearl Gold'},
    {legoColourId:308,   name:'Dark Brown',              hex: '#372100', BrickLinkId: 120, BrickLinkName: 'Dark Brown'},
    {legoColourId:312,   name:'Medium Nougat',           hex: '#AA7D55', BrickLinkId: 150, BrickLinkName: 'Medium Nougat'},
    {legoColourId:315,   name:'Silver Metallic',         hex: '#8C8C8C', BrickLinkId: 95, BrickLinkName: 'Flat Silver'},
    {legoColourId:316,   name:'Titanium Metallic',       hex: '#3E3C39', BrickLinkId: 77, BrickLinkName: 'Pearl Dark Gray'},
    {legoColourId:321,   name:'Dark Azur',               hex: '#469BC3', BrickLinkId: 153, BrickLinkName: 'Dark Azur'},
    {legoColourId:322,   name:'Medium Azur',             hex: '#68C3E2', BrickLinkId: 156, BrickLinkName: 'Medium Azur'},
    {legoColourId:323,   name:'Aqua',                    hex: '#D3F2EA', BrickLinkId: 152, BrickLinkName: 'Light Aqua'},
    {legoColourId:324,   name:'Medium Lavender',         hex: '#A06EB9', BrickLinkId: 157, BrickLinkName: 'Medium Lavender'},
    {legoColourId:325,   name:'Lavender',                hex: '#CDA4DE', BrickLinkId: 154, BrickLinkName: 'Lavender'},
    {legoColourId:326,   name:'Spring Yellowish Green',  hex: '#E2F99A', BrickLinkId: 158, BrickLinkName: 'Yellowish Green'},
    {legoColourId:329,   name:'White Glow',              hex: '#F5F3D7', BrickLinkId: 159, BrickLinkName: 'Glow In Dark White '},
    {legoColourId:330,   name:'Olive Green',             hex: '#77774E', BrickLinkId: 155, BrickLinkName: 'Olive Green'},
];
export default Colours;

